<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="authentication"
    targetNamespace="http://localhost:8000/authentication"
    xmlns="http://localhost:8000/authentication"
    xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<wsdl:message name="authRequest">
        <wsdl:part name="email" type="xs:string"/>
        <wsdl:part name="password" type="xs:string"/>
    </wsdl:message>
	
	<wsdl:message name="authResponse">
        <wsdl:part name="Login" type="xs:boolean"/>
    </wsdl:message>
	
	<wsdl:portType name="authBank">

        <wsdl:operation name="request">
            <wsdl:input message="authRequest"/>
            <wsdl:output message="authResponse"/>
        </wsdl:operation>

    </wsdl:portType>
	
	<wsdl:binding name="authBankSoapBind" type="authBank">
        <soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="save">
            <soap:operation soapAction="save"/>
            <wsdl:input>
                <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="literal"/>
            </wsdl:output>
        </wsdl:operation>
        
    </wsdl:binding>
    <wsdl:service name="AuthService">
        <wsdl:port binding="authBankSoapBind" name="authPort">
            <soap:address location="http://localhost:8001/imam"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>